#!/bin/csh
# Nov17 Quique: epsilonbig is now calculated inside irradiado, so eps
# can be given any value. Also some changes to paths and naming of files.
# Sep17 Quique: new parameter D2G, the dust-to-gas mass ratio. Also, new parameter
# image that can be set to 'thin' or 'thick', depending on which type of image
# one needs. Thus, there is now just one jobfile for the images.
# Jun17 Quique: AMAXW, the amax of the dust grains in the wall, by default
# will be the same as in the disk, but it can be changed independently from the disk.

#this is script to run mm synthesized images with intensity
#as output
#modified on 10july08

set labelend='test'

#main directory ------------------------------------
set MAIN=/project/bu-disks/shared/DIAD
set MAINCODE=$MAIN/CODEf77_081109
#OPACITY
set DIROPA=$MAINCODE/OPACIDADES
#COMUN
set DIRCOMUN=$MAINCODE/COMUN
#POLVO
set MAINPOL=$MAIN/POLVO

#stellar parameters  -------------------------------
set MSTAR='1.0' #in MSUN
set TSTAR='4730' #in K
set RSTAR='1.5'  #in Rsun
set DISTANCIA='140'  #in pasecs
set MDOT='7.2e-9' #in Msun/yr

#disk parameters ------------------------------------
set ALPHA='0.002'
set MUI='0.57'  #cosine of inclination angle
set RDISK='300'  #radius of disk in AU

#dust-to-gas mass ratio -------------------------------
set D2G='0.0065'

#settling------------------------
set EPS='0.0001'
#------------------------

#size of the small grains in the
#upper disk
set AMAXS='0.25'
set lamaxs='amax0p25'

#this sets size of grains in midplane
set AMAXB='1000'
set lamaxb='amax1mm'

#inputs for wall
set TEMP=130. #temperature at inner edge (i.e., wall) of disk
set ALTINH='1' #scale height of wall
#dust grain sizes in the wall----------------
set AMAXW=$AMAXS
set lamaxw=$lamaxs

#set WLFILE=$DIRCOMUN/wlfile_1300um_1pt.ent
set WL=1300 # wavelength in microns

# Should the disk be thick or thin at this lambda?
# (i.e., run thick or thin version of image?)
set image='thin' # set to 'thin' or 'thick'

set IIMAGEDISK='1' #output is fort.10 in grid and fort.62
set IIMAGEWALL='1'

##########   Do not change anything below here  ################
########## (unless you know what you are doing) ################
# relative abundances
set silab=0.004
set grafab=0.0025
set iceab=0.00001
set troiab=0.00000001
set labelsilab='1'
set labgrafab='1'
set labiceab='1'

set AMINW='0.005'
set PW='3.5'
set TEMPW=$TEMP
set TAUMAXL='1.5' #radial "depth" of wall
set ESCRIBIR='1' #write image? no=0,yes=1, extinguished=2
set EST='0'             #include star in image? no=0,yes=1, extinguished=2
set TAUEXT='0'          #give tau if choose extinguished

set labeps=e$EPS
set labcom=$labelend
set ISUB='1'
set IALB='0'

#subdirectories----------------------------------------
set DIRPRODISK=$MAINCODE/IMAGES/PROGRAMS/DISK
set DIRPROWALL=$MAINCODE/IMAGES/PROGRAMS/WALL
set DIRPROADD=$MAINCODE/IMAGES/ADD
#set DIRPROTHIN=$MAIN/PROGRAMS/THIN

#programs --------------------------------------------------------
if ($image == 'thin') then
set PRODISK=$DIRPRODISK/image_wall_disk_othin
else
set PRODISK=$DIRPRODISK/image_wall_disk_othick
endif
set PROWALL=$DIRPROWALL/wall_grid_t23
set PROADD=$DIRPROADD/add_RF2
#set PRORIN=$DIRPROWALL/radiowall
#set PROTHIN=$DIRPROTHIN/thin

set extension=a$ALPHA.irr.$labelend.e$EPS.$lamaxs\_$lamaxb.dat
#set extension=$TSTAR.mp$MDOT.a$ALPHA.irr.$labcom\_ts14ng.p3p5.$labeps.$lamaxs\_$lamaxb.dat
set FILESALIRR=fort14.$extension
set salidaimage=idiskw.$image.w.mu$MUI.rd$RDISK.tw$TEMPW.$extension.$labelend.WL$WL


#begin SEDT-----------------------------------------

#files for wall
set FILELONGOPA=$DIROPA/longitudes_all.ent

set FILESILWALL=sil.p3p5.$lamaxw.g.$labcom
#set FILESILWALL=$MAINPOL/SIL/mgfe/sil.p3p5.$lamaxw.g.ab$labelsilab.extinc
set FILEORGWALL=$MAINPOL/GRAF/graf.p3p5.$lamaxw.g.ab$labgrafab.extinc
set FILEICEWALL=$MAINPOL/H2OICE/h2oice.p3p5.$lamaxw.g.ab$labiceab.extinc.wb08
set FILETROI=$MAINPOL/TROI/troi.p3p5.$lamaxw.g.ab0p000768.extinc

set FILESILB=$MAINPOL/SIL/mgfe/sil.p3p5.$lamaxb.g.ab$labelsilab.extinc
set FILEGRAFB=$MAINPOL/GRAF/graf.p3p5.$lamaxb.g.ab$labgrafab.extinc
set FILESILS=sil.p3p5.$lamaxs.g.$labcom
#set FILESILS=$MAINPOL/SIL/mgfe/sil.p3p5.$lamaxs.g.ab$labelsilab.extinc
set FILEGRAFS=$MAINPOL/GRAF/graf.p3p5.$lamaxs.g.ab$labgrafab.extinc

set LFILESIL=prueba
set FILEOUTSED=fort.17.H$ALTINH.$LFILESIL.ami$AMINW.amx$AMAXW.p$PW.$MUI.t$TEMPW.$labelend.WL$WL
set FILEIMAGE=fort.1.H$ALTINH.$LFILESIL.ami$AMINW.amx$AMAXW.p$PW.$MUI.t$TEMPW.tau$TAUEXT.$labelend.WL$WL

#input files disk image----------------------------------------------
set LONG1=$DIROPA/longitudes_tio.ent
set LONG2=$DIROPA/longco.mod
set OPATIO1=$DIROPA/opa_tio_t100_p0.dat
set OPATIO2=$DIROPA/opa_tio_t158.489_p0.dat
set OPATIO3=$DIROPA/opa_tio_t251.189_p0.dat
set OPATIO4=$DIROPA/opa_tio_t398.107_p0.dat
set OPATIO5=$DIROPA/opa_tio_t630.957_p0.dat
set OPATIO6=$DIROPA/opa_tio_t1000_p0.dat
set OPATIO7=$DIROPA/opa_tio_t1584.89_p0.dat
set OPATIO8=$DIROPA/opa_tio_t2511.89_p0.dat
set OPATIO9=$DIROPA/opa_tio_t3981.07_p0.dat
set OPATIO10=$DIROPA/opa_tio_t6309.57_p0.dat
set OPATIO11=$DIROPA/opa_tio_t10000_p0.dat
set FILEPOBLA=$DIROPA/poblaciones8feb05.dat
set FILEHIGHT=$DIROPA/hight.dat
set OPAMOL1=$DIROPA/tio.dat
set OPAMOL2=$DIROPA/cow1.dat
set OPAMOL3=$DIROPA/cof1.dat
set OPAMOL4=$DIROPA/cow2.dat
set OPAMOL5=$DIROPA/cof2.dat
set OPAMOL6=$DIROPA/auman.dat


echo IIMAGEWALL=$IIMAGEWALL

if ($IIMAGEWALL == 1) then
echo calculating imagewall
if ($ESCRIBIR == 0) then
$PROWALL << EOD
$TEMP
$MDOT
$MSTAR $TSTAR $RSTAR
$MUI
$silab $grafab $troiab $iceab
$DISTANCIA
$RDISK
$ALTINH
$TAUMAXL
$WL
$ESCRIBIR
$FILEOUTSED
$FILELONGOPA
$FILESILWALL
$FILEORGWALL
$FILETROI
$FILEICEWALL
EOD
echo $FILEOUTSED

else
$PROWALL << EOD
$TEMP
$MDOT
$MSTAR $TSTAR $RSTAR
$MUI
$silab $grafab $troiab $iceab
$DISTANCIA
$RDISK
$ALTINH
$TAUMAXL
$WL
$ESCRIBIR
$EST
$TAUEXT
$FILEIMAGE
$FILEOUTSED
$FILELONGOPA
$FILESILWALL
$FILEORGWALL
$FILETROI
$FILEICEWALL
EOD
echo $FILEOUTSED
echo $FILEIMAGE

endif
endif



echo calculating image disk
#rm -f $salidaimage
$PRODISK << EOD
$salidaimage
$FILESALIRR
$D2G
$silab $grafab $iceab
$FILESILB
$FILEGRAFB
$FILESILS
$FILEGRAFS
$WL
$FILEIMAGE
$ISUB
$DISTANCIA
$RSTAR
$RDISK
$TSTAR
$MUI
$LONG1
$LONG2
$OPATIO1
$OPATIO2
$OPATIO3
$OPATIO4
$OPATIO5
$OPATIO6
$OPATIO7
$OPATIO8
$OPATIO9
$OPATIO10
$OPATIO11
$FILEPOBLA
$FILEHIGHT
$OPAMOL1
$OPAMOL2
$OPAMOL3
$OPAMOL4
$OPAMOL5
$OPAMOL6
EOD
echo $salidaimage
cp fort.10 grid.$salidaimage
echo grid.$salidaimage
endif

set fitsname=$salidaimage.fits

$PROADD << EOD
$salidaimage
$fitsname
$DISTANCIA
$RDISK
EOD

echo $fitsname

#rm -f $FILEOUTSED
#rm -f $FILEIMAGE

exit
